### ISSUE TITLE
DAG4: snowflake_load_dag

### ISSUE THREAD

**Issue by mangodm-web** [TFTrashaimase/tft-victory-planner#28]
- S3로부터 Snowflake에 데이터 가져오는 DAG 작성
- 필요하면, Silver Layer 데이터 추가하는 것과 하나의 DAG으로 구성(이후 논의 필요)

**Comment by koreakseong22** [comment]
- 앞선 'TFT_Riot_API_Dag' 및 'tft_champion_data_ingestion'의 실행이 모두 성공했을 경우 Trigger를 통해 해당 DAG 실행. 
- S3에 적재된 raw data들을 Snowflake에 적재하는 DAG.

**Comment by koreakseong22** [comment]
추후 docker-compose.yml 파일 내에서 Snowflake Connection을 위한 작업 예정.
