### ISSUE TITLE
최종 보고서 작성

### ISSUE THREAD

**Issue by cbbsjj0314** [TFTrashaimase/tft-victory-planner#46]
# 작업 내용
아래 최종 보고서 링크에서 목차별 담당자를 정하고 분담하여 작성
몇몇 일부에게 최대한 덜 몰리도록 초안을 작성해 보고, 후에 좀 더 잘 아시는 분 혹은 다 함께 검토하면 좋을 것 같아요
**2. 데이터 파이프라인 설계**의 경우, 각 항목마다 이미지를 넣을 수 있을 것 같은데 이 부분도 일단 각 담당자가 그려보고 서하님, 다미님한테 검토 받으면 될 듯 (가능하다면 멘토님도)
- [최종 보고서](https://www.notion.so/d54e1f573e6d48ebb1fa92ddd78ea42b?pvs=4)
- [ChatGPT가 만든 최초 양식](https://www.notion.so/8408b0589c9d41d7b2cefd54d3335b51?pvs=4)

# To do
### 목차별 담당자 지정
이름이 여러 개인 건 제가 생각하는 그 항목 후보자들 오름차순 입니다 ("내가 왜?" 시전하면 반영함)
인프라 구성 부분은 찬영님이 혼자 다 쓰셔야 할 것 같아서 이름 1개만 썼습니다
- [x] 1. 프로젝트 개요
- [ ] 2. 데이터 파이프라인 설계
  - [ ] 시스템 아키텍처: 김동희, 이헌성, 정서하
  - [ ] 데이터 흐름 아키텍처: 김학성, 이헌성, 최범준, 허다미
  - [ ] 데이터 레이어 설계: 김동희, 박찬영, 정서하, 허다미
  - [ ] DAG 구조: 김학성, 이헌성, 최범준, 허다미
- [ ] 3. 기술 구현 세부 내용
  - [ ] 데이터 수집: 김학성, 이헌성, 최범준
  - [ ] Docker 사용: 김학성, 이헌성
  - [ ] 데이터 저장 및 처리: 이헌성, 정서하, 허다미
  - [ ] 인프라 구성: **박찬영**
- [ ] 4. 분석 결과
  - [ ] 차트 구성: 김동희, 박찬영
- [ ] 5. 결론 및 한계: 각자 느낀 게 있다면 논의 후 작성
- [ ] 6. 회고
  - 이건 각자 작성이긴 한데 **회고 양식도 필요하다 vs. 자유롭게 작성**
  - 회고 양식에 대해 예를 들면, 잘한 점, 아쉬운 점, 다음 프로젝트 때 개선해 볼 점 등등

### 디자인
- [ ] 대제목, 중제목, 소제목의 텍스트 스타일 지정 (제목1, 2, 3등)
  - 1 2 3 이런 식으로 붙은 걸 대제목이라고 칭했는데 **중/소제목도 3-1. 3-1-1. 이런 식으로 작성하기 vs. 중/소제목은 그냥 숫자 빼기**
- [ ] 팀 색깔 정하기
  - 목차 제목에 사용할 색이라든지
- [ ] 또 머가 있을지? (**패션왕 찬영님, 미적 감각 1인자 서하님** 의견 있으신지.. 그 외 신흥강자 환영)

**Comment by CoffeeIsNak** [comment]
찬영님만 이름에 볼드체가 들어간 것 같은데 주인공인가요?

**Comment by cbbsjj0314** [comment]
아니오 독박입니다

**Comment by cbbsjj0314** [comment]
아하 독박입니다
