### ISSUE TITLE
도커 이미지 구성

### ISSUE THREAD

**Issue by cbbsjj0314** [TFTrashaimase/tft-victory-planner#6]
+파이썬 패키지 버전 관리

- [ ] Airflow 버전: 2.9.1
- [ ] 네트워크 설정
- [ ] 환경변수 설정
- [ ] flake8, black, sqlfluff
- [ ] 그 외 필요한 것 있으면 추가

**Comment by koreakseong22** [comment]
## 'TFT-Victory-Planner' Airflow를 배포할 수 있는 Docker Image 구성 완료하였습니다.

**[Docker Image 구조]**

tftrashaimase/
├── docker-compose.yml # 다중 컨테이너 도커 애플리케이션 빌
├── Dockerfile  # 커스텀 도커 이미지
├── requirements.txt  # Python 패키지 의존성
├── .env # 환경변수 저장
├── .gitignore # Github에 push-pull 되지 않아야 할 실행 파일들
├── .dockerignore # 도커 빌드 시에 들어가지 않는 파일들 
└── dags/  # DAG 파일들이 위치한 폴더
